import os
import logging
from typing import Any, Dict, Union
from neuro_san.interfaces.coded_tool import CodedTool

# ReportLab imports
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

try:
    from _paths import request_dir
except ImportError:
    from coded_tools.migration_intelligence._paths import request_dir

logger = logging.getLogger(__name__)

class ReportRenderTool(CodedTool):
    """CodedTool that consolidates findings and renders a structured PDF report."""

    def invoke(self, args: Dict[str, Any], sly_data: Dict[str, Any]) -> Union[Dict[str, Any], str]:
        logger.info("********** ReportRenderTool started **********")
        request_id = args.get("request_id")
        security_summary = args.get("security_summary", "No security analysis provided.")
        cost_summary = args.get("cost_summary", "No cost estimation provided.")
        reliability_summary = args.get("reliability_summary", "No reliability checks provided.")

        if not request_id:
            return {"error": "Missing request_id"}

        # Define paths (dynamic)
        dir_path = request_dir(request_id)
        pdf_path = os.path.join(dir_path, "report.pdf")

        logger.info(f"Rendering PDF report to: {pdf_path}")

        try:
            # Build SimpleDocTemplate document
            doc = SimpleDocTemplate(
                pdf_path,
                pagesize=letter,
                rightMargin=54,
                leftMargin=54,
                topMargin=54,
                bottomMargin=54
            )

            story = []
            styles = getSampleStyleSheet()

            # Custom styles
            title_style = ParagraphStyle(
                'ReportTitle',
                parent=styles['Normal'],
                fontName='Helvetica-Bold',
                fontSize=22,
                leading=26,
                textColor=colors.HexColor('#0f2e4d'),
                spaceAfter=15
            )

            h1_style = ParagraphStyle(
                'SectionHeading',
                parent=styles['Normal'],
                fontName='Helvetica-Bold',
                fontSize=14,
                leading=18,
                textColor=colors.HexColor('#2e6fba'),
                spaceBefore=15,
                spaceAfter=8,
                keepWithNext=True
            )

            body_style = ParagraphStyle(
                'ReportBody',
                parent=styles['BodyText'],
                fontName='Helvetica',
                fontSize=10,
                leading=14,
                textColor=colors.HexColor('#333333'),
                spaceAfter=10
            )

            meta_style = ParagraphStyle(
                'MetaText',
                parent=styles['Normal'],
                fontName='Helvetica',
                fontSize=9,
                leading=12,
                textColor=colors.HexColor('#666666')
            )

            # Title & Metadata
            story.append(Paragraph("Cloud Migration Analysis Report", title_style))
            story.append(Paragraph(f"<b>Request ID:</b> {request_id}", meta_style))
            story.append(Paragraph("<b>Generated By:</b> Neuro-SAN CI/CD Intelligence Layer", meta_style))
            story.append(Spacer(1, 15))

            # Metadata Table
            meta_data = [
                ["Status", "IN REVIEW (Phase 1 Approved)"],
                ["Environment Gating", "48-Hour Approval Window Initiated"]
            ]
            meta_table = Table(meta_data, colWidths=[150, 350])
            meta_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8f9fa')),
                ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor('#495057')),
                ('PADDING', (0,0), (-1,-1), 6),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e9ecef')),
                ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold')
            ]))
            story.append(meta_table)
            story.append(Spacer(1, 15))

            # 1. Risk & Compliance (Security)
            story.append(Paragraph("1. Risk & Compliance Evaluation", h1_style))
            # Format text linebreaks
            sec_formatted = security_summary.replace("\n", "<br/>")
            story.append(Paragraph(sec_formatted, body_style))
            story.append(Spacer(1, 10))

            # 2. Cost Analysis (FinOps)
            story.append(Paragraph("2. FinOps Cost Projections", h1_style))
            cost_formatted = cost_summary.replace("\n", "<br/>")
            story.append(Paragraph(cost_formatted, body_style))
            story.append(Spacer(1, 10))

            # 3. System Resilience (Reliability)
            story.append(Paragraph("3. System Resilience & Uptime Validation", h1_style))
            rel_formatted = reliability_summary.replace("\n", "<br/>")
            story.append(Paragraph(rel_formatted, body_style))
            story.append(Spacer(1, 10))

            # Build Document
            doc.build(story)
            logger.info("PDF build successful.")

        except Exception as e:
            logger.error(f"Error rendering PDF: {e}")
            return {"error": f"Failed to build PDF: {e}"}

        logger.info("********** ReportRenderTool completed **********")
        return {
            "status": "success",
            "file_path": pdf_path
        }
